include:
  - project: 'automation/laravel-ci'
    ref: 0.0.20
    file: '.laravel-js-framework-template.yml'

variables:
  MYSQL_USER: app
  MYSQL_PASSWORD: secret
  MYSQL_DATABASE: rebase
  MAINTENANCE_MODE: "true"
