include:
  - project: 'automation/laravel-ci'
    ref: latest
    file: '.laravel-template.yml'

variables:
  MYSQL_USER: app
  MYSQL_PASSWORD: secret
  MYSQL_DATABASE: rebase
  MAINTENANCE_MODE: "true"
  STAGE_PHP_BINARY: "php8.2"
  DEFAULT_PHP_IMAGE_VERSION: "git.beeproger.io:4567/beeproger-docker-images/php-8.2:latest"
  ENABLE_FRONTEND: "true"
